// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANtZHWKFZ2U-r41yRTLbIWAJzbTVgpxfU',
    appId: '1:94263283566:web:99113ea39efc4dcc883b7f',
    messagingSenderId: '94263283566',
    projectId: 'local-setup-tutorial',
    authDomain: 'local-setup-tutorial.firebaseapp.com',
    storageBucket: 'local-setup-tutorial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQcujZjKLndpA9V0xNm3d4H7fBOQQiCcs',
    appId: '1:94263283566:android:393bc7df0cdf5cc9883b7f',
    messagingSenderId: '94263283566',
    projectId: 'local-setup-tutorial',
    storageBucket: 'local-setup-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEcrUcTwcU7vIZaE7CBbTYSlMcFAnqoRo',
    appId: '1:94263283566:ios:8cd2a4ff794448bb883b7f',
    messagingSenderId: '94263283566',
    projectId: 'local-setup-tutorial',
    storageBucket: 'local-setup-tutorial.appspot.com',
    iosClientId: '94263283566-jthmunec3asie7mhns2pk21p6nqgp3k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.localSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEcrUcTwcU7vIZaE7CBbTYSlMcFAnqoRo',
    appId: '1:94263283566:ios:8cd2a4ff794448bb883b7f',
    messagingSenderId: '94263283566',
    projectId: 'local-setup-tutorial',
    storageBucket: 'local-setup-tutorial.appspot.com',
    iosClientId: '94263283566-jthmunec3asie7mhns2pk21p6nqgp3k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.localSetup',
  );
}
